import { reportStyles } from "./report.styles.js";
import { generatePieChart } from "./chart.service.js";
export const reportTemplate = (
  user: any,
  expenses: any[],
  income: number,
  expense: number
) => {

const chart = generatePieChart(
income,
expense
);
  return `
<!DOCTYPE html>

<html>

<head>

<style>

${reportStyles}

</style>

</head>

<body>

<div class="header">

<img
src="file:///${process.cwd().replace(/\\/g,"/")}/assets/logo.png"
class="logo"
/>

<div class="company">
AI Expense Tracker
</div>

<div class="subtitle">
Financial Report
</div>

</div> 

<div class="company">

AI Expense Tracker

</div>

<div class="subtitle">

Financial Report

</div>

</div>

<h3>User Information</h3>

<p><b>Name:</b> ${user.name}</p>

<p><b>Email:</b> ${user.email}</p>

<p><b>Date:</b> ${new Date().toLocaleString()}</p>

<div class="summary">

<div class="card">

<h3>💰 Total Income</h3>

₹${income}

</div>

<div class="card">

<h3>💸 Total Expense</h3>

₹${expense}

</div>

<div class="card">

<h3>💵 Current Balance</h3>

₹${income - expense}

</div>


</div>

<div class="executive-summary">
  <h2>Executive Summary</h2>

  <p>
    This report provides an overview of the user's financial activity.
    It summarizes income, expenses and remaining balance.
    The purpose is to identify spending trends and help improve budgeting.
  </p>
</div>

<h2>Income vs Expense</h2>

<div style="text-align:center; margin:20px 0;">
  <img
    src="${chart}"
    style="width:350px;"
  />
</div>

<h3>Expenses</h3>

<table>

<tr>

<th>Title</th>

<th>Amount</th>

<th>Category</th>

<th>Type</th>

<th>Date</th>

</tr>

${expenses
  .map(
    (e) => `
<tr>

<td>${e.title}</td>

<td>₹${e.amount}</td>

<td>${e.category}</td>

<td>${e.type}</td>

<td>${new Date(e.date).toLocaleDateString()}</td>

</tr>
`
  )
  .join("")}

</table>
<div class="footer">

Generated by AI Expense Tracker

<br>

Confidential Financial Report

<br>

© 2026 All Rights Reserved

</div>

</body>

</html>
`;
};