import { PDF } from "./constants.js";

export function drawFooter(
  doc: PDFKit.PDFDocument,
) {
  const footerY =
    doc.page.height - 40;

  doc
    .strokeColor(PDF.BORDER)
    .moveTo(
      PDF.PAGE_MARGIN,
      footerY - 8,
    )
    .lineTo(
      doc.page.width -
        PDF.PAGE_MARGIN,
      footerY - 8,
    )
    .stroke();

  doc
    .fillColor(PDF.SUBTEXT)
    .font("Helvetica")
    .fontSize(9)
    .text(
      "Generated by AI Expense Tracker",
      PDF.PAGE_MARGIN,
      footerY,
      {
        lineBreak: false,
      },
    );
}